var ST=function(a,b){window.addEventListener("load",function(){var c=document.getElementById(a),d=c.clientWidth,i=c.clientHeight;c.getContext&&b(new ST.st(a,d,i))},!1)};Array.prototype.remove=function(a,b){var c=this.slice((b||a)+1||this.length);this.length=a<0?this.length+a:a;return this.push.apply(this,c)};String.prototype.trim=function(){return this.replace(/^\s*([\s\S]*\S)\s*$/,"$1")};
ST.frameclip=function(a,b,c,d){this.name=a;this.layer=d;this.cid=this.layer.cid;this.ctx=this.layer.ctx;this.width=ST.st.instances[this.cid].width;this.height=ST.st.instances[this.cid].height;this.frameOffset=b;this.lastFrame=c;this.shapes=[];this.callbackfired=!1;this.randomCount=0;this.playMode="";this.tracks=[];this.effects=[];this.sclY=this.sclX=this.scl=1;this.strokeW=this.rot=this.top=this.left=0;this.strokeHex="00000000";this.strokeRGBA=ST.st.prototype.hexRGBA(this.strokeHex);this.strokeR=
this.strokeRGBA[0];this.strokeG=this.strokeRGBA[1];this.strokeB=this.strokeRGBA[2];this.strokeA=this.strokeRGBA[3];this.fillHex="00000000";this.fillRGBA=ST.st.prototype.hexRGBA(this.fillHex);this.fillR=this.fillRGBA[0];this.fillG=this.fillRGBA[1];this.fillB=this.fillRGBA[2];this.fillA=this.fillRGBA[3];this.opac=1;this.centerX=this.width/2;this.centerY=this.height/2;this.cuts=[];this.sprites={}};ST.frameclip.prototype.sprite=function(a,b){this.sprites[a]=b;return this};
ST.frameclip.prototype.shape=function(a,b,c,d,i,j,k){for(var e=0;e<this.shapes.length;e++)if(this.shapes[e].name==a)return this.shapes[e];a=new ST.shapeobject(a,b,c,d,i,j,k,this);this.shapes.push(a);return a};ST.frameclip.prototype.track=function(a){for(var b=0;b<this.tracks.length;b++)if(this.tracks[b].property==a)return this.tracks[b];this.tracks[this.tracks.length]=new ST.trackprop(a,this);return this.tracks[this.tracks.length-1]};
ST.frameclip.prototype.draw=function(){var a=ST.st.prototype.radians;this.frame=this.layer.frame;this.ctx.save();if(this.tracks.length>0){for(var b=0;b<this.tracks.length;b++){var c=this.tracks[b],d=this.tracks[b].property;if(c.keys.length<=2){var i=c.keys[0],j=c.keys[1]||c.keys[0];ST.st.prototype.engine(this,this.frame,d,i,j)}else for(var k=0;k<c.keys.length;k++)if(i=c.keys[k],j=c.keys[k+1]||c.keys[k],this.frame>=i.frame&&this.frame<=j.frame){ST.st.prototype.engine(this,this.frame,d,i,j);break}}this.ctx.translate(this.left+
this.centerX,this.top+this.centerY);this.ctx.rotate(a(this.rot));this.sclX!=this.sclY?this.ctx.scale(this.sclX,this.sclY):this.ctx.scale(this.scl,this.scl);this.ctx.translate(-this.centerX,-this.centerY);this.ctx.doFill=!0;this.ctx.fillStyle="rgba("+this.fillR+","+this.fillG+","+this.fillB+","+this.fillA+")";this.ctx.strokeStyle="rgba("+this.strokeR+","+this.strokeG+","+this.strokeB+","+this.strokeA+")";if(this.transform)a=this.transform,this.ctx.transform(a[0],a[1],a[2],a[3],a[4],a[5]);this.ctx.lineWidth=
this.strokeW;this.ctx.globalAlpha=this.opac;this.ctx.beginPath();this.ctx.moveTo(0,0);this.ctx.lineTo(this.width,0);this.ctx.lineTo(this.width,this.height);this.ctx.lineTo(0,this.height);this.ctx.closePath();this.ctx.fill();this.ctx.stroke()}for(b=0;b<this.shapes.length;b++)this.shapes[b].draw(this.frame);for(var e in this.sprites)this.sprites[e].frame<=this.frame?this.sprites[e].draw():this.sprites[e].frame=0;this.ctx.restore()};
ST.Img=function(a){this.url=a;this.type="image";this.top=this.left=this.centerY=this.centerX=0;this.scl=1;this.rot=0;this.opac=1;this.transform=[1,0,0,1,0,0];this.f=[];this.a=[];this.c=0;this.tracks=[]};ST.Img.prototype.add=function(a,b){this.a[this.c]=a;this.f[this.c]=b;this.c++};
ST.Img.prototype.render=function(){ctx.save();ctx.translate(this.left+this.centerX,this.top+this.centerY);ctx.scale(this.scl,this.scl);ctx.rotate(st.prototype.radians(this.rot));ctx.translate(-this.centerX,-this.centerY);for(var a=0;a<this.f.length;a++)this.f[a](this.a[a]);ctx.globalAlpha=1;ctx.restore()};ST.keyframe=function(a,b,c){this.frame=a;this.value=b;this.easing=c};ST.keyframe.prototype.val=function(a){this.v=a};ST.keyframe.prototype.ease=function(a){this.easing=a};
ST.layer=function(a,b,c){this.name=a;this.depth=b;this.frameclips={};this.mc=c;this.cid=this.mc.cid;this.ctx=this.mc.ctx};ST.layer.prototype.frameclip=function(a,b,c){this.frameclips[a]=new ST.frameclip(a,b,c,this);return this.frameclips[a]};ST.layer.prototype.draw=function(){this.frame=this.mc.frame;for(var a in this.frameclips){var b=this.frameclips[a];this.frame>=b.frameOffset&&this.frame<=b.lastFrame&&b.draw()}};
ST.movieclip=function(a,b,c,d){this.name=a;this.layers=[];this.movieclips=[];this.frame=0;this.length=b;this.loop=c||!1;this.cid=d.cid;this.ctx=d.ctx};ST.movieclip.prototype.layer=function(a,b){var c=new ST.layer(a,b,this);this.layers.push(c);for(var d=[],i=0;i<this.layers.length;i++)d.push(this.layers[i].depth);d.sort(ST.st.sortNumber);var j=[];for(i=0;i<d.length;i++)for(var k=0;k<this.layers.length;k++)this.layers[k].depth==d[i]&&(j[i]=this.layers[k]);this.layers=j;return c};
ST.movieclip.prototype.draw=function(){this.drawLayers();if(this.frame==this.length-1){if(this.loop)this.frame=0}else this.frame++};ST.movieclip.prototype.drawLayers=function(){for(var a=0;a<this.layers.length;a++)this.layers[a].draw()};
ST.shapeobject=function(a,b,c,d,i,j,k,e){this.name=a;this.url=b;this.extension=b.split(/([\.][a-zA-Z0-9]+)/)[1];this.obj=[];this.mode=c||"svg";this.cid=e.cid;this.ctx=e.ctx;this.checkMemory();this.left=d||0;this.top=i||0;this.scl=j||1;this.rot=k||0;this.opac=1;this.centerY=this.centerX=0;if(c==="svg")this.centerX=this.obj.width/2,this.centerY=this.obj.height/2;this.type="shape";this.tracks=[];this.effects=[];this.shapes=[];this.transform=[1,0,0,1,0,0]};
ST.shapeobject.prototype.checkMemory=function(){var a=ST.st.instances[this.cid];if(a.urlIndex.length>0){urlMatch=!1;for(var b=0;b<a.urlIndex.length;b++)if(a.urlIndex[b]===this.url){switch(this.mode){case "img":this.obj=a.loadImage(this.url);break;case "svg":this.obj=a.loadSVG(this.url,this.mode)}urlMatch=!0;break}if(urlMatch===!1){a.urlIndex[a.urlIndex.length]=this.url;switch(this.mode){case "img":a.ajaxMem[a.urlIndex.length]=a.loadImage(this.url);break;case "svg":a.ajaxMem[a.urlIndex.length]=a.loadSVG(this.url,
this.mode)}this.obj=a.ajaxMem[a.urlIndex.length]}}else{a.urlIndex[a.urlIndex.length]=this.url;switch(this.mode){case "img":a.ajaxMem[a.urlIndex.length]=a.loadImage(this.url);break;case "svg":a.ajaxMem[a.urlIndex.length]=a.loadSVG(this.url,this.mode)}this.obj=a.ajaxMem[a.urlIndex.length]}};
ST.shapeobject.prototype.track=function(a){for(var b=0;b<this.tracks.length;b++)if(this.tracks[b].property==a)return this.tracks[b];this.tracks[this.tracks.length]=new ST.trackprop(a,this);return this.tracks[this.tracks.length-1]};
ST.shapeobject.prototype.draw=function(a){var b=ST.st.prototype.radians,c,d;for(c=0;c<this.tracks.length;c++){var i=this.tracks[c],j=this.tracks[c].property;if(i.keys.length<=2){var k=i.keys[0],e=i.keys[1]||i.keys[0];ST.st.prototype.engine(this,a,j,k,e)}else for(d=0;d<this.tracks[c].keys.length;d++)if(k=this.tracks[c].keys[d],e=i.keys[d+1]||i.keys[d],a>=k.frame&&a<=e.frame){ST.st.prototype.engine(this,a,j,k,e);break}}this.ctx.save();this.ctx.translate(this.left+this.centerX,this.top+this.centerY);
this.ctx.rotate(b(this.rot));this.ctx.scale(this.scl,this.scl);this.ctx.translate(this.left-this.centerX,this.top-this.centerY);this.ctx.globalAlpha=this.opac;this.ctx.transform(this.transform[0],this.transform[1],this.transform[2],this.transform[3],this.transform[4],this.transform[5]);this.obj.render();this.ctx.restore()};
ST.st=function(a,b,c){this.cid=a;this.ctx=document.getElementById(this.cid).getContext("2d");this.urlIndex=[];this.ajaxMem=[];this.tl="";this.mspf=20;this.frame=0;this.width=b;this.height=c;this.paused=!1;this.movieclips=[];this.lastFrame=0;ST.st.instances[a]=this};ST.st.instances={};ST.st.prototype.setFps=function(a){this.mspf=Math.floor(1E3/a)};ST.st.prototype.defaults={ease:"linear",debug:!1};ST.st.prototype.has=function(a,b){return b.indexOf(a,0)>-1};
ST.st.prototype.hexRGBA=function(a){return function(a){var c=[];a.replace(/(..)/g,function(a){c.push(parseInt(a,16))});return c}(a)};ST.st.prototype.toHex=function(a){a=a.toString(16);a.length<2&&(a="0".concat(a));return a};ST.st.prototype.radians=function(a){return a/180*Math.PI};ST.st.prototype.ease=function(a,b,c,d,i,j){return i*c/j+d};
ST.st.prototype.engine=function(a,b,c,d,i){var j=this.ease,k=this.hexRGBA;if(b==i.frame){var e=i.value;switch(c){case "left":a.left=e;break;case "top":a.top=e;break;case "centerX":a.centerX=e;break;case "centerY":a.centerY=e;break;case "scl":a.scl=e;break;case "rot":a.rot=e;break;case "mx":a.transform=[e[0],e[1],e[2],e[3],e[4],e[5]];break;case "strokeWeight":a.strokeW=e;break;case "stroke":var f=k(e);a.strokeR=f[0];a.strokeG=f[1];a.strokeB=f[2];a.strokeA=1/255*f[3];break;case "fill":f=k(e);a.fillR=
f[0];a.fillG=f[1];a.fillB=f[2];a.fillA=1/255*f[3];break;case "opac":a.opac=e}}else{var m=d.easing;b-=d.frame;e=d.value;f=i.value-d.value;var g=i.frame-d.frame;switch(c){case "left":a.left=j(m,0,b,e,f,g);break;case "top":a.top=j(m,0,b,e,f,g);break;case "centerX":a.centerX=j(m,0,b,e,f,g);break;case "centerY":a.centerY=j(m,0,b,e,f,g);break;case "scl":a.scl=j(m,0,b,e,f,g);break;case "rot":a.rot=j(m,0,b,e,f,g);break;case "mx":f=[];for(k=0;k<e.length;k++)f[k]=i.value[k]-d.value[k];a.transform=[j(m,0,b,
e[0],f[0],g),j(m,0,b,e[1],f[1],g),j(m,0,b,e[2],f[2],g),j(m,0,b,e[3],f[3],g),j(m,0,b,e[4],f[4],g),j(m,0,b,e[5],f[5],g)];break;case "strokeWeight":a.strokeW=j(m,0,b,e,f,g);break;case "stroke":d=k(d.value);i=k(i.value);a.strokeR=parseInt(j(m,0,b,d[0],i[0]-d[0],g));a.strokeG=parseInt(j(m,0,b,d[1],i[1]-d[1],g));a.strokeB=parseInt(j(m,0,b,d[2],i[2]-d[2],g));a.strokeA=1/255*j(m,0,b,d[3],i[3]-d[3],g);break;case "fill":d=k(d.value);i=k(i.value);a.fillR=parseInt(j(m,0,b,d[0],i[0]-d[0],g));a.fillG=parseInt(j(m,
0,b,d[1],i[1]-d[1],g));a.fillB=parseInt(j(m,0,b,d[2],i[2]-d[2],g));a.fillA=1/255*j(m,0,b,d[3],i[3]-d[3],g);break;case "opac":a.opac=j(m,0,b,e,f,g)}}};ST.st.prototype.start=function(){var a=this;this.timer=setInterval(function(){a.drawNextFrame();if(a.frame>a.lastFrame-1)a.loop?a.frame=0:clearInterval(a.timer)},this.mspf)};ST.st.prototype.mc=function(a){this.movieclips.push(a);if(a.length>this.lastFrame)this.lastFrame=a.length};
ST.st.prototype.drawNextFrame=function(){this.frame<=this.lastFrame&&this.ctx.clearRect(0,0,this.width,this.height);for(var a=0;a<this.movieclips.length;a++)this.movieclips[a].draw();this.frame++};ST.st.prototype.loadImage=function(a){var b=this,c=new ST.Img,d=new Image;d.src=a;c.add([],function(){b.ctx.drawImage(d,0,0)});return c};
ST.st.prototype.loadSVG=function(a){var b=this,c=ST.st.prototype.has,d=ST.st.prototype.hexRGBA,i={},j={},k={},e=[],f,m,g,u=new DOMParser,h=new ST.SVG(a,this.ctx),z=function(a){for(var e=!1,p=!1,q=[],r=[],s=/rgb\(([^\)]+)\)/,n=function(a,b){for(var d=RegExp(a,"g"),c=0,e=[];e[c]=d.exec(b);)c++;return e},w=function(){var a=f.getAttribute("transform");(v=n("(translate[(])([0-99. -]+)(,)([0-99. -]+)",a)[0])&&h.add([v[2],v[4]],function(a){b.ctx.translate(a[0],a[1])},g);(v=n("(matrix[(])([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)([)])",
a)[0])&&h.add([v[2],v[4],v[6],v[8],v[10],v[12]],function(a){b.ctx.transform(a[0],a[1],a[2],a[3],a[4],a[5])},g)},C=function(a){var f=p=e=!1,t=!1,A=1,B=1,o=1;if(a=a.getAttribute("style")){a=a.trim().split(";");for(var x=0;x<a.length;x++){var l=a[x].split(":");if(!(l.length<2))switch(o=l[0].trim(),l=l[1].trim(),o){case "opacity":o=l;h.add(o,function(a){b.ctx.globalAlpha=a},g);break;case "stroke-width":o=parseFloat(l);h.add(o,function(a){b.ctx.lineWidth=a},g);break;case "stroke-linecap":h.add(l,function(a){b.ctx.lineCap=
a},g);break;case "stroke-linejoin":h.add(l,function(a){b.ctx.lineJoin=a},g);break;case "stroke-miterlimit":o=parseFloat(l);h.add(o,function(a){b.ctx.miterLimit=a},g);break;case "fill-opacity":B=l;break;case "fill":l!="none"&&(e=!0,c("url(#",l)?(o=n("(url[(]#)(.[^)]+)",l)[0][2],l=m.getElementById(o),l.nodeName=="pattern"?h.add(j[o],function(a){b.ctx.transform.apply(b.ctx,a[0]);b.ctx.fillStyle=a[1]},g):(f=!0,h.add(i[o],function(a){b.ctx.fillStyle=a},g))):c("#",l)?(r=d(l.substr(1,6)),f=!1):c("rgb",l)&&
(r=l.replace(s,"$1"),f=!1));break;case "stroke-opacity":A=l;break;case "stroke":l!="none"&&(p=!0,c("url(#",l)?(o=n("(url[(]#)(.[^)]+)",l)[0][2],l=m.getElementById(o),l.nodeName=="pattern"?h.add(j[o],function(a){b.ctx.transform.apply(b.ctx,a[0]);b.ctx.strokeStyle=a[1]},g):(t=!0,h.add(i[o],function(a){b.ctx.strokeStyle=a},g))):c("#",l)?(q=d(l.substr(1,6)),t=!1):c("rgb",l)&&(q=l.replace(s,"$1"),t=!1));break;case "clip-path":l=l.replace(/"/g,""),o=n("(url[(]#)(.[^)]+)",l)[0][2],h.add(k[o],function(a){b.ctx.beginPath();
a=n("([a-zA-Z][0-9- .,]+[^a-zA-Z])|(z|Z)",a.getAttribute("d"));for(var d=0;d<a.length-1;d++){var c=0;switch(a[d][0][0]){case "M":c=n("([0-9-.]+){1,2}",a[d][0]);b.ctx.moveTo(c[0][0],c[1][0]);break;case "C":c=n("([0-9-.]+){1,6}",a[d][0]);b.ctx.bezierCurveTo(c[0][0],c[1][0],c[2][0],c[3][0],c[4][0],c[5][0]);break;case "Q":c=n("([0-9-.]+){1,6}",a[d][0]);b.ctx.quadraticCurveTo(c[0][0],c[1][0],c[2][0],c[3][0]);break;case "A":c=n("([0-9-.]+){1,6}",a[d][0]);b.ctx.arcTo(c[0][0],c[1][0],c[2][0],c[3][0],c[4][0],
c[5][0]);break;case "L":c=n("([0-9-.]+){1,2}",a[d][0]),b.ctx.lineTo(c[0][0],c[1][0])}}b.ctx.clip()},g)}}f==!1&&e==!0&&(f="rgba("+r[0]+","+r[1]+","+r[2]+","+B+")",h.add(f,function(a){b.ctx.fillStyle=a},g));t==!1&&p==!0&&(f="rgba("+q[0]+","+q[1]+","+q[2]+","+A+")",h.add(f,function(a){b.ctx.strokeStyle=a},g))}},u=function(){h.add(0,function(){b.ctx.beginPath()},g);w(f);for(var a=n("([a-zA-Z][0-9- .,]+[^a-zA-Z])|(z|Z)",f.getAttribute("d")),c=0;c<a.length-1;c++){var d=0;switch(a[c][0][0]){case "M":d=n("([0-9-.]+){1,2}",
a[c][0]);h.add([d[0][0],d[1][0]],function(a){b.ctx.moveTo(a[0],a[1])},g);break;case "C":d=n("([0-9-.]+){1,6}",a[c][0]);h.add([d[0][0],d[1][0],d[2][0],d[3][0],d[4][0],d[5][0]],function(a){b.ctx.bezierCurveTo(a[0],a[1],a[2],a[3],a[4],a[5])},g);break;case "Q":d=n("([0-9-.]+){1,6}",a[c][0]);h.add([d[0][0],d[1][0],d[2][0],d[3][0]],function(a){b.ctx.quadraticCurveTo(a[0],a[1],a[2],a[3])},g);break;case "A":d=n("([0-9-.]+){1,6}",a[c][0]);h.add([d[0][0],d[1][0],d[2][0],d[3][0],d[4][0],d[5][0]],function(a){b.ctx.arcTo(a[0],
a[1],a[2],a[3],a[4],a[5])},g);break;case "L":d=n("([0-9-.]+){1,2}",a[c][0]);h.add([d[0][0],d[1][0]],function(a){b.ctx.lineTo(a[0],a[1])},g);break;case "Z":h.add(0,function(){b.ctx.closePath()},g);break;case "z":h.add(0,function(){b.ctx.closePath()},g)}}C(f);e&&h.add(0,function(){b.ctx.fill()},g);p&&h.add(0,function(){b.ctx.stroke()},g)},E=function(){w(f);var a=f.getAttribute("width"),d=f.getAttribute("height"),c=f.getAttribute("x"),i=f.getAttribute("y");C(f);e&&h.add([c,i,a,d],function(a){b.ctx.fillRect(a[0],
a[1],a[2],a[3])},g);p&&h.add([c,i,a,d],function(a){b.ctx.strokeRect(a[0],a[1],a[2],a[3])},g)},F=function(a){var b=a.getElementsByTagName("path")[0];a=a.getAttribute("id");k[a]=b},G=function(a){var d=a.getAttribute("id"),c=a.getElementsByTagName("image")[0].getAttribute("xlink:href"),e=new Image;e.src=c;a=n("(matrix[(])([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)([)])",a.getAttribute("patternTransform"));e=b.ctx.createPattern(e,"no-repeat");j[d]=[[a[0][2],
a[0][4],a[0][6],a[0][8],a[0][10],a[0][12]],e]},D=function(a,c){var e=a.getAttribute("id");switch(c){case "linear":var f=a.getAttribute("x1"),g=a.getAttribute("y1"),j=a.getAttribute("x2"),k=a.getAttribute("y2");i[e]=b.ctx.createLinearGradient(f,g,j,k);for(f=0;g=a.getElementsByTagName("stop")[f];){f++;for(j=0;k=g.getAttribute("style").split(";")[j];){j++;var l=g.getAttribute("offset");k=k.split(":");switch(k[0].trim()){case "stop-color":var h;h=k[1];h.indexOf("#")!=-1?h=d(h.substr(1,6)):(h=h.replace(s,
"$1"),h=h.split(","));break;case "stop-opacity":var m=k[1]}}i[e].addColorStop(l,"rgba("+h[0]+","+h[1]+","+h[2]+","+m+")")}break;case "radial":f=a.getAttribute("cx");g=a.getAttribute("cy");j=a.getAttribute("r");k=a.getAttribute("fx");var n=a.getAttribute("fy");i[e]=b.ctx.createRadialGradient(f,g,0,k,n,j);for(f=0;g=a.getElementsByTagName("stop")[f];){f++;for(j=0;k=g.getAttribute("style").split(";")[j];)switch(j++,l=g.getAttribute("offset"),k=k.split(":"),k[0].trim()){case "stop-color":h=k[1];h.indexOf("#")!=
-1?h=d(h.substr(1,6)):(h=h.replace(s,"$1"),h=h.split(","));break;case "stop-opacity":m=k[1]}i[e].addColorStop(l,"rgba("+h[0]+", "+h[1]+","+h[2]+","+m+")")}}},y=0;y<a.childNodes.length;y++){f=a.childNodes[y];curTagName=f.tagName;if(a.tagName=="svg")g=f.id;switch(curTagName){case "defs":z(f);break;case "linearGradient":D(f,"linear");break;case "radialGradient":D(f,"radial");break;case "pattern":G(f);break;case "clipPath":F(f);break;case "g":h.add([],function(){b.ctx.save()},g);w(f);z(f);h.add([],function(){b.ctx.restore()},
g);break;case "path":h.add([],function(){b.ctx.save()},g);u(f);h.add([],function(){b.ctx.restore()},g);break;case "rect":h.add([],function(){b.ctx.save()},g),E(f),h.add([],function(){b.ctx.restore()},g)}}};(function(){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);m=u.parseFromString(b.responseText,"text/xml");e=m.documentElement;h.width=parseFloat(e.getAttribute("width"));h.height=parseFloat(e.getAttribute("height"));z(e,"svg")})();return h};ST.st.sortNumber=function(a,b){return a-b};
ST.SVG=function(a,b){this.url=a;this.type="ST.SVGobject";this.top=this.left=this.centerY=this.centerX=0;this.scl=1;this.rot=0;this.opac=1;this.transform=[1,0,0,1,0,0];this.f=[];this.a=[];this.c=0;this.tracks=[];this.ctx=b};ST.SVG.prototype.add=function(a,b){this.a[this.c]=a;this.f[this.c]=b;this.c++};
ST.SVG.prototype.render=function(){this.ctx.save();this.ctx.translate(this.left+this.centerX,this.top+this.centerY);this.ctx.scale(this.scl,this.scl);this.ctx.rotate(ST.st.prototype.radians(this.rot));this.ctx.translate(-this.centerX,-this.centerY);for(var a=0;a<this.f.length;a++)this.f[a](this.a[a]);this.ctx.globalAlpha=1;this.ctx.restore()};ST.trackprop=function(a,b){this.property=a;this.keys=[];this.shape=b};ST.trackprop.prototype.track=function(a){return this.shape.track(a)};
ST.trackprop.prototype.key=function(a,b,c){this.keys.push(new ST.keyframe(a,b,c||ST.st.prototype.defaults.ease));a=[];for(b=0;b<this.keys.length;b++)a[b]=this.keys[b].frame;a.sort(ST.st.sortNumber);c=[];for(b=0;b<this.keys.length;b++)for(var d=0;d<this.keys.length;d++)a[b]==this.keys[d].frame&&(c[b]=this.keys[d]);this.keys=c;return this};
